export const DRAW_BORDER = 'DRAW_BORDER'
export const INIT_BALL = 'INIT_BALL'
export const INIT_PADDLE = 'INIT_PADDLE'
export const INIT_BLOCKS = 'INIT_BLOCKS'
export const INIT_BREAKS = 'INIT_BREAKS'

export const SET_BALL_POS = 'SET_BALL_POS'
export const SET_PADDLE_POS = 'SET_PADDLE_POS'
export const BREAKS_PROJ_X = 'BREAKS_PROJ_X'
export const BREAKS_PROJ_Y = 'BREAKS_PROJ_Y'
export const SET_X_REVERSE = 'SET_X_REVERSE'
export const SET_Y_REVERSE = 'SET_Y_REVERSE'
